{{- if .Values.persistence.enabled }}
{{- if not .Values.persistence.persistentVolumeClaim.existingClaim }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "wiremock.fullname" . }}
  labels:
    {{- include "wiremock.labels" . | nindent 4 }}
  {{- if eq .Values.persistence.resourcePolicy "keep" }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.persistentVolumeClaim.accessMode }}
  {{- if .Values.persistence.persistentVolumeClaim.storageClass }}
  {{- if (eq "-" .Values.persistence.persistentVolumeClaim.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.persistence.persistentVolumeClaim.storageClass }}"
  {{- end }}
  {{- end }}
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.persistence.persistentVolumeClaim.size }}
{{- end }}
{{- end }}